FROM eclipse-temurin:8
MAINTAINER ejep509 <zbr1nghso29y@donottrackplus.info>
WORKDIR /usr/local/share/
COPY seventeenth-0.0.1-SNAPSHOT.jar ./
CMD ["java", "-jar", "/usr/local/share/seventeenth-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
